# Generated by Django 4.1.1 on 2023-03-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='loc_country_raw',
            field=models.TextField(default=''),
        ),
    ]
